# Generated by Django 3.2.6 on 2021-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodel',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
