# Generated by Django 3.2.6 on 2021-08-25 15:53

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursesmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.document_images_file_path),
        ),
    ]
