# Generated by Django 3.2.6 on 2021-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursesmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
