# Generated by Django 3.2.6 on 2021-08-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210825_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
