# Generated by Django 3.2.6 on 2021-08-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_sectionmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionmodel',
            name='description',
        ),
    ]
