# Generated by Django 3.2.6 on 2021-08-25 08:24

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('bio', models.TextField(max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=teachers.models.document_images_file_path)),
            ],
        ),
    ]
