# Generated by Django 3.2.6 on 2021-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
