# Generated by Django 3.2.6 on 2021-08-20 09:54

from django.db import migrations, models
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.document_images_file_path),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('prefer-not-to-say', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('lagos', 'Lagos State'), ('ogun', 'Ogun State'), ('oyo', 'Oyo State'), ('abuja', 'Abuja (FCT) State'), ('rivers', 'Rivers State'), ('abia', 'Abia State'), ('adamawa', 'Adamawa State'), ('akwa-ibon', 'Akwa Ibon State'), ('bauchi', 'Bauchi State'), ('bayelsa', 'Bayelsa State'), ('benue', 'Benue State'), ('borno', 'Borno State'), ('cross-rivers', 'Cross Rivers State'), ('deltaz', 'Delta State'), ('ebonyi', 'Ebonyi State'), ('edo', 'Edo State'), ('ekitiz', 'Ekiti State'), ('enugu', 'Enugu State'), ('gombe', 'Gombe State'), ('imo', 'Imo State'), ('jigawa', 'Jigawa State'), ('kaduna', 'Kaduna State'), ('kano', 'Kano State'), ('katsina', 'Katsina State'), ('kebbi', 'Kebbi State'), ('kogi', 'Kogi State'), ('kwara', 'Kwara State'), ('nasarawa', 'Nasarawa State'), ('niger', 'Niger State'), ('ondo', 'Ondo State'), ('plateau', 'Sokoto State'), ('sokoto', 'Plateau State'), ('taraba', 'Taraba State'), ('yobe', 'Yobe State'), ('zamfara', 'Zamfara State')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='referal_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
